### ISSUE TITLE
Tag for the latest Pypi release is missing

### ISSUE THREAD

**Issue by firefly-cpp** [Tigge/openant#101]
Thanks, @tuna-f1sh

**Comment by tuna-f1sh** [comment]
I have 'released' it manually but don't intend to always do this. FYI, the tag is always present since that's how the workflow publishes the PyPI package: https://github.com/Tigge/openant/releases/tag/v1.3.1

I think I commented out the GitHub release because it would not work without repository changes form the @Tigge: https://github.com/Tigge/openant/blob/master/.github/workflows/build.yml#L90

I'm not sure what your workflow is but the PyPI always has latest and if you want to download a specific tag it's always at https://github.com/Tigge/openant/releases/tag/v1.3.1
